name = "LocalJuliaRepo"
uuid = "c5a0c350-42d6-4cea-90f3-86d29b2553fb"
repo = "git@github.com:joschakrug/LocalJuliaRepo.git"

[packages]
15489a28-470a-4c47-be98-4174d0f03947 = { name = "GriddedFunctions", path = "G/GriddedFunctions" }
